name: Build and test

# README:
#
# The semantics for running shell commands in GitHub actions is non-obvious. Please read
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
# before modifying this file. Our strategy is to rely on the built-in (unspecified) shell, and
# explicitly set the shell settings we want (with `set -eo pipefail`) at the beginning of any
# bash script. For more information on these settings, see `man bash`.
#
# GitHub Actions files can be difficult to modify with confidence, because testing changes often
# requires pushing to a branch and running CI remotely. To make this process easier, consider
# the following:
#
# 1) Use Visual Studio Code with the GitHub Actions Extension (github.vscode-github-actions).
#    This allows you to check the validity of your action schema and syntax without pushing to a
#    branch.
# 2) Use https://github.com/nektos/act to run your CI steps locally. Note this will only work with
#    steps run on Linux platforms, as `act` is implemented with Docker containers.

on:
  workflow_call:
    inputs:
      build-type:
        description: 'The build configuration type'
        default: 'debug'
        required: false
        type: string
      git-ref:
        description: 'The git ref to checkout'
        required: false
        type: string

env:
  swift-version: '6.2'

jobs:
  build-linux:
    name: "Build and test: ${{ matrix.host.os }}/${{ inputs.build-type }}"
    strategy:
      fail-fast: false
      matrix:
        host: [
          { type: linux, os: ubuntu-latest,
            build-options: "",
            test-options: "--enable-code-coverage"
          }
        ]

    runs-on: ${{ matrix.host.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
        ref: ${{ inputs.git-ref }}

    - name: Setup swift
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: ${{ env.swift-version }}

    - name: Build (${{ inputs.build-type }})
      id: build
      run: |
        set -eo pipefail
        swift build -c ${{ inputs.build-type }} ${{ matrix.host.build-options }}
        BUILD_DIR=$(swift build -c ${{ inputs.build-type }} --show-bin-path)
        echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV

  build-native-macos:
    name: "Build and test: ${{ matrix.host.os }}/${{ inputs.build-type }}"
    strategy:
      fail-fast: false
      matrix:
        host: [
          {
            type: macos, os: macos-15,
            build-options: "--build-tests -Xswiftc -enable-testing",
            # No coverage support on MacOS
            test-options: ""
          }
        ]

    runs-on: ${{ matrix.host.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        ref: ${{ inputs.git-ref }}

    - name: Setup swift
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: ${{ env.swift-version }}

    - run: swift --version

    - name: Build (${{ inputs.build-type }})
      id: build
      run: |
        set -eo pipefail
        swift build -c ${{ inputs.build-type }} ${{ matrix.host.build-options }}
        BUILD_DIR=$(swift build -c ${{ inputs.build-type }} --show-bin-path)
        echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV

  build-native-windows:
    name: "Build and test: windows-latest/${{ inputs.build-type }}"
    # strategy:
    #   fail-fast: false
    runs-on: windows-latest
    steps:
    - name: Setup swift
      uses: compnerd/gha-setup-swift@main
      with:
        branch: swift-${{ env.swift-version }}-release
        tag: ${{ env.swift-version }}-RELEASE

    - uses: actions/checkout@v4
      with:
        submodules: 'true'
        ref: ${{ inputs.git-ref }}

    - name: Build (${{ inputs.build-type }})
      id: build
      run: |
        $BUILD_DIR = swift build -c ${{ inputs.build-type }} --show-bin-path
        echo BUILD_DIR=$BUILD_DIR
        echo BUILD_DIR=$BUILD_DIR >> $env:GITHUB_ENV
        swift build -c ${{ inputs.build-type }}

  build-distributable:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15, macos-15-intel, windows-2025, windows-11-arm]
        swift: ["6.2"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ inputs.git-ref }}

      - name: Set up Swift ${{ matrix.swift }} on ${{ matrix.os }}
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: ${{ matrix.swift }}

      - name: Build in release mode
        run: swift build -c release --verbose --product hylo-language-server --static-swift-stdlib

      - name: Get the distributable path
        id: get-distributable-path
        run: |
          BIN_PATH=$(swift build -c release --product hylo-language-server --static-swift-stdlib --show-bin-path)
          ${BIN_PATH}/hylo-language-server --help
          echo "path=${BIN_PATH}" >> $GITHUB_OUTPUT

        shell: bash
      - name: Upload the distributable
        uses: actions/upload-artifact@v4
        with:
            name: hylo-language-server-${{ runner.os }}-${{ runner.arch }}
            path: ${{ steps.get-distributable-path.outputs.path }}
